%
% Melody Shih 26.2.2019
% (Adaped from make_1_9_cell_At.m by Antti Hannukainen / 4.3.2018 / Otaniemi)
%
%-----------------------------------------------
%
% This function creates elemenwise coefficient vector At 
% corresponding to the coefficient field A. The coefficient field A has 
% value 1 / 9 with 50 / 50 probability in cell z + (0,1) z \in Z^2.
%
%
%  CALLING SYNTAX IS
% 
%  function At = make_cmin_cmax_cell_At(r, t2c, cmin, cmax)
%
%       r    = size of the domain Ur. 
%       t2c  = 2 x Nt matrix mapping triangles to cells. Triangle i belongs
%              to the cell (t2c(1,i)-1)x(t2c(2,i)-1)x(t2c(1,i))x(t2c(2,i)). 
%              Matrix t2c is generated by the function make_Ur_mesh.m.
%   
%       At   = Nt-vector of the value of coefficient A over mesh such that
%              A_|K = At(K) for ever triangle index K=1,..,Nt. 
%
% see assembly_P1.m and make_Ur_mesh.m
%


function At = make_cmin_cmax_cell_At(r, t2c, cmin, cmax, p)
if nargin == 4
  p = 0.5;
end

R = rand(r);
Acell = zeros(r);
Acell( R < p) = cmax;
Acell( R >= p) = cmin;

ind = sub2ind([r r],t2c(1,:), t2c(2,:) );
At = Acell(ind);
